name: Hello Kotlin CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'hello-kotlin/**'
      - '.github/workflows/hello-kotlin.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'hello-kotlin/**'
      - '.github/workflows/hello-kotlin.yml'

jobs:
  test:
    name: Build and Test Hello Kotlin
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: hello-kotlin
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-hello-kotlin-${{ hashFiles('hello-kotlin/**/*.gradle*', 'hello-kotlin/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-hello-kotlin-
          
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Build project
      run: ./gradlew build --no-daemon
      
    - name: Run tests
      run: ./gradlew test --no-daemon
      
    - name: Generate test report
      run: ./gradlew jacocoTestReport --no-daemon
      if: always()
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: hello-kotlin-test-results
        path: hello-kotlin/build/test-results/test/
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: hello-kotlin-coverage-reports
        path: hello-kotlin/build/reports/jacoco/ 